---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Config
- type: document
  path: content/config.md
  label: Config
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Unterseiten
- type: document
  path: content/pages/about.md
  label: About
- type: document
  path: content/pages/contact.md
  label: Contact
- type: document
  path: content/pages/imprint.md
  label: Imprint
- type: document
  path: content/pages/privacy-policy.md
  label: Privacy Policy
upload_dir: "."
public_path: ''
front_matter_path: content/assets
use_front_matter_path: true
file_template: "./:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
