name: CI/CD KrisKodira Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      
    - name: NPM install
      run: npm i
      
    - name: NPM run build
      run: npm run build
    
    - name: Publish to docs for GitHub Pages
      run: mv ./public ./docs
